version: '3'
volumes:
    dados:
networks:
    banco:
    web:
    fila:
services:
    db:
        image: postgres:11
        volumes:
            # volume com os dados
            - dados:/var/lib/postgresql/data
            # scripts de banco de dados -> Mapeia a pasta script para dentro do container
            - ./scripts:/scripts
            # Conversão: diretório onde ficam scripts que devem ser executados durante a inicialização
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - banco
    frontend:
        image: nginx:latest
        volumes:
            - ./web:/usr/share/nginx/html
            # Configuração do proxy reverso (mapeamento de volume para arquivos)
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        networks:
            - web
        depends_on:
            - app
    app:
        image: python:3.6
        volumes:
            # Aplicação
            - ./app:/app
        working_dir: /app
        command: bash ./app.sh
        networks:
            - banco
            - web
            - fila
        depends_on:
            - db
            - queue
        environment:
            - DB_NAME=db_errado
    queue:
        image: redis:latest
        networks:
            - fila
    worker:
        build: worker
        volumes:
            # Worker
            - ./worker:/worker
        working_dir: /worker
        command: worker.py
        networks:
            - fila
        depends_on:
            - queue
